#ifndef __CECONFIG_H__
#define __CECONFIG_H__
// CEFilter Component List:
#define CE_MODULES_COREDLL 1
#define CE_MODULES_KCOREDLL 1
#define CE_MODULES_NK 1
#define CE_MODULES_NKLOADER 1
#define CE_MODULES_OEM 1
#define CE_MODULES_OALIOCTL 1
#define CE_MODULES_PGORT90 1
#define CE_MODULES_LVMOD_FULL 1
#define CE_MODULES_LVMOD_STUB 1
#define CE_MODULES_REGEXTDEV 1
#define CE_MODULES_SHELL 1
#define CE_MODULES_LOADDBG 1
#define CE_MODULES_SHELLCELOG 1
#define CE_MODULES_BPINSTANTIATOR 1
#define CE_MODULES_DLLHEAPINFOEXT 1
#define CE_MODULES_DEVHEALTH 1
#define CE_MODULES_DEVHEALTHDLL 1
#define CE_MODULES_RELFSD 1
#define CE_MODULES_RELFSDEXT 1
#define CE_MODULES_LPCD 1
#define CE_MODULES_LPCRT 1
#define CE_MODULES_DSTSVC 1
#define CE_MODULES_GPSID 1
#define CE_MODULES_GPSAPI 1
#define CE_MODULES_NOTIFY 1
#define CE_MODULES_CMNET 1
#define CE_MODULES_CMSERVICE 1
#define CE_MODULES_CMCSPDTPT 1
#define CE_MODULES_CMCSPIP 1
#define CE_MODULES_CMCSPWWAN 1
#define CE_MODULES_WSCMEXT 1
#define CE_MODULES_PROXYSVC 1
#define CE_MODULES_PROXYDBS 1
#define CE_MODULES_RMNET 1
#define CE_MODULES_RSPBASIC 1
#define CE_MODULES_RSPCELLULAR 1
#define CE_MODULES_CFMSERVICE 1
#define CE_MODULES_CFMCLIENT 1
#define CE_MODULES_ASYNCMAC 1
#define CE_MODULES_UNIMODEM 1
#define CE_MODULES_SERVICESFILTER 1
#define CE_MODULES_SERVICESSTART 1
#define CE_MODULES_SERVICESENUM 1
#define CE_MODULES_SERVICES 1
#define CE_MODULES_TCPIP 1
#define CE_MODULES_NETIO 1
#define CE_MODULES_NSI 1
#define CE_MODULES_NSIPROXY 1
#define CE_MODULES_WINNSI 1
#define CE_MODULES_NSISVC 1
#define CE_MODULES_TCPIPREG 1
#define CE_MODULES_BFE 1
#define CE_MODULES_FWPUCLNT 1
#define CE_MODULES_IKEEXT 1
#define CE_MODULES_FWPKCLNT 1
#define CE_MODULES_DNSAPI 1
#define CE_MODULES_WINSOCK 1
#define CE_MODULES_AFD 1
#define CE_MODULES_NETIO 1
#define CE_MODULES_WS2 1
#define CE_MODULES_WS2INSTL 1
#define CE_MODULES_WSPM 1
#define CE_MODULES_NSPM 1
#define CE_MODULES_WS2K 1
#define CE_MODULES_WS2SERV 1
#define CE_MODULES_SSLLSP 1
#define CE_MODULES_RTL8139 1
#define CE_MODULES_E100BEX 1
#define CE_MODULES_NE2000 1
#define CE_MODULES_DHCP 1
#define CE_MODULES_DHCPV6L 1
#define CE_MODULES_RTLNWIFI 1
#define CE_MODULES_AR6K_NWF 1
#define CE_MODULES_NDISUIO 1
#define CE_MODULES_VEIM 1
#define CE_MODULES_DHCPSRV 1
#define CE_MODULES_NDIS 1
#define CE_MODULES_PPP 1
#define CE_MODULES_TAPI 1
#define CE_MODULES_POLICYXML 1
#define CE_MODULES_IRI 1
#define CE_MODULES_SECUR32 1
#define CE_MODULES_NTLMSSP 1
#define CE_MODULES_NTLMSSP_SVC 1
#define CE_MODULES_SPNEGO 1
#define CE_MODULES_SCHANNEL 1
#define CE_MODULES_CREDMAN 1
#define CE_MODULES_CRYPT32 1
#define CE_MODULES_NCRYPT 1
#define CE_MODULES_KEYISO 1
#define CE_MODULES_MSASN1 1
#define CE_MODULES_ALPCD 1
#define CE_MODULES_RPCRT4 1
#define CE_MODULES_REDIR 1
#define CE_MODULES_NETBIOS 1
#define CE_MODULES_CEPERF_MODULE 1
#define CE_MODULES_BTA2DP 1
#define CE_MODULES_SBC 1
#define CE_MODULES_BTAVDTP 1
#define CE_MODULES_BTAVCTP 1
#define CE_MODULES_BTAVRCP 1
#define CE_MODULES_OBEXSRVR 1
#define CE_MODULES_BTD 1
#define CE_MODULES_BTDRT 1
#define CE_MODULES_BTHUNIV 1
#define CE_MODULES_BTHUTIL 1
#define CE_MODULES_BTHUSB 1
#define CE_MODULES_BTHSDIO 1
#define CE_MODULES_BTHUART 1
#define CE_MODULES_BTHCSR 1
#define CE_MODULES_SETPROXY 1
#define CE_MODULES_IPHLPAPI 1
#define CE_MODULES_NETLOG 1
#define CE_MODULES_NETLOGCTL 1
#define CE_MODULES_KBDA1 1
#define CE_MODULES_KBDHEB 1
#define CE_MODULES_KBDTH0 1
#define CE_MODULES_KBDINHIN 1
#define CE_MODULES_KBDINMAR 1
#define CE_MODULES_KBDINPUN 1
#define CE_MODULES_KBDINTEL 1
#define CE_MODULES_KBDINGUJ 1
#define CE_MODULES_KBDINKAN 1
#define CE_MODULES_KBDINTAM 1
#define CE_MODULES_KBDUS 1
#define CE_MODULES_KBDJPN 1
#define CE_MODULES_KBDJPNNEC 1
#define CE_MODULES_KBDKOR 1
#define CE_MODULES_KBDRUS 1
#define CE_MODULES_BCRYPT 1
#define CE_MODULES_CCFGSVC 1
#define CE_MODULES_AUDIODRV 1
#define CE_MODULES_UIPROXY 1
#define CE_MODULES_FLASHMDD 1
#define CE_MODULES_FLASHPART 1
#define CE_MODULES_CXPORT 1
#define CE_MODULES_SENSORS 1
#define CE_MODULES_BATTDRVR 1
#define CE_MODULES_NLEDDRVR 1
#define CE_MODULES_NLEDSTUBPDD 1
#define CE_MODULES_TIMEZONES 1
#define CE_MODULES_EXFAT 1
#define CE_MODULES_FATUTIL 1
#define CE_MODULES_DISKCACHE 1
#define CE_MODULES_DEVICE 1
#define CE_MODULES_REGENUM 1
#define CE_MODULES_BUSENUM 1
#define CE_MODULES_GIISR 1
#define CE_MODULES_MMTIMER 1
#define CE_MODULES_PCI 1
#define CE_MODULES_SERIAL 1
#define CE_MODULES_8042KEYBOARD 1
#define CE_MODULES_NOPKEYBOARD 1
#define CE_MODULES_RAMDISK 1
#define CE_MODULES_SDBUS 1
#define CE_MODULES_SDMEMORY 1
#define CE_MODULES_USBHOST 1
#define CE_MODULES_USBD 1
#define CE_MODULES_USBOTG 1
#define CE_MODULES_USBFN 1
#define CE_MODULES_USBFNMDD 1
#define CE_MODULES_RNDISFN 1
#define CE_MODULES_SERIALUSBFN 1
#define CE_MODULES_COMPOSITEFN 1
#define CE_MODULES_UNIFIEDBLOCK 1
#define CE_MODULES_UNIFIEDPAIR 1
#define CE_MODULES_COREOSLAUNCH 1
#define CE_MODULES_CEDDK 1
#define CE_MODULES_CACHEFILT 1
#define CE_MODULES_RAWFS 1
#define CE_MODULES_ROMFILTER 1
#define CE_MODULES_IMGUPD 1
#define CE_MODULES_PACKAGEINFOAPI 1
#define CE_MODULES_UPDATEVALIDATOR 1
#define CE_MODULES_IMGFS 1
#define CE_MODULES_MSPART 1
#define CE_MODULES_WMPART 1
#define CE_MODULES_ZLIB 1
#define CE_MODULES_XMLLITE 1
#define CE_MODULES_POLICYENGINE 1
#define CE_MODULES_POLICYEXT 1
#define CE_MODULES_FILESYS 1
#define CE_MODULES_FILESYS_ULDR 1
#define CE_MODULES_FSDMGR 1
#define CE_MODULES_ROMFSD 1
#define CE_MODULES_STOREAPI 1
#define CE_MODULES_COREOS_DAT 1
#define CE_MODULES_RSAENH 1
#define CE_MODULES_DSSDH 1
#define CE_MODULES_CECOMPR 1
#define CE_MODULES_OPENMPCE 1
#define CE_MODULES_DEVHEALTH 1
#define CE_MODULES_DEVHEALTHDLL 1
#define CE_MODULES_TOOLHELP 1
#define CE_MODULES_VMINI 1
#define CE_MODULES_RT_TESTS 1
#define DCOM_MODULES_ATL 1
#define DCOM_MODULES_DLLHOST 1
#define DCOM_MODULES_DCOMSSD 1
#define DCOM_MODULES_OLE32 1
#define DCOM_MODULES_OLEAUT32 1
#define DCOM_MODULES_RPCRT4LEGACY 1
#define DCOM_MODULES_KOLE32 1
#define DCOM_MODULES_KOLEAUT32 1
#define DCOM_MODULES_UUID 1
#define GDIEX_MODULES_GDIPLUS 1
#define GDIEX_MODULES_IMAGING 1
#define NETCFV37_MODULES_DOTNETV37_SMARTFON 1
#define SQLCOMPACT_MODULES_EDB 1
#define SQLCOMPACT_MODULES_SQLCOMPACTMP 1
#define SQLCOMPACT_MODULES_SQLCOMPACT 1
#define SQLCOMPACT_MODULES_EDB 1
#define SERVERS_MODULES_WLIDSVC 1
#define SERVERS_MODULES_MSIDCRL 1
#define SERVERS_MODULES_PPCRLCONFIG_PRODUCTION 1
#define SERVERS_MODULES_PPCRLCONFIG_INT 1
#define SERVERS_MODULES_LFTESTPLUGIN 1
#define SERVERS_MODULES_LSTIMEPLUGIN 1
#define SERVERS_MODULES_LFGPSPROVIDER 1
#define SERVERS_MODULES_LFRILPROVIDER 1
#define SERVERS_MODULES_LFWIFIPROVIDER 1
#define SERVERS_MODULES_LSWIFICELLRESOLVER 1
#define SERVERS_MODULES_LFLATLONRESOLVER 1
#define SERVERS_MODULES_LFPLACESRESOLVER 1
#define SERVERS_MODULES_LSALGOSRESOLVER 1
#define SERVERS_MODULES_LSCROWDSOURCING 1
#define SERVERS_MODULES_LFCLIENTPROXY 1
#define SERVERS_MODULES_LFSVC 1
#define SERVERS_MODULES_LFAPI 1
#define SERVERS_MODULES_LFMANAGEDAPI 1
#define SERVERS_MODULES_LOCATIONUX 1
#define SERVERS_MODULES_LOCATIONUXRES 1
#define SERVERS_MODULES_LOCATIONUXSPLASH 1
#define SERVERS_MODULES_ONEX 1
#define SERVERS_MODULES_WLANSEC 1
#define SERVERS_MODULES_WLANMSM 1
#define SERVERS_MODULES_WLANEXT 1
#define SERVERS_MODULES_WLANUTIL 1
#define SERVERS_MODULES_WLANSVC 1
#define SERVERS_MODULES_WLANAPI 1
#define SERVERS_MODULES_WLANTOOL 1
#define SERVERS_MODULES_NWIFI 1
#define SERVERS_MODULES_ONEX 1
#define SERVERS_MODULES_WLANSEC 1
#define SERVERS_MODULES_WLANMSM 1
#define SERVERS_MODULES_WLANUTIL 1
#define SERVERS_MODULES_WLANSVC 1
#define SERVERS_MODULES_WLANAPI 1
#define SERVERS_MODULES_WLANTOOL 1
#define SERVERS_MODULES_WLANCFGSP 1
#define SERVERS_MODULES_EAPPHOST 1
#define SERVERS_MODULES_EAPPCFG 1
#define SERVERS_MODULES_EAPPPRXY 1
#define SERVERS_MODULES_EAPSVC 1
#define SERVERS_MODULES_EAPP3HST 1
#define SERVERS_MODULES_EAP3SVC 1
#define SERVERS_MODULES_EAP 1
#define SERVERS_MODULES_EAPCHAP 1
#define SERVERS_MODULES_EAPTLS 1
#define SERVERS_MODULES_TASKSCHEDULER 1
#define SERVERS_MODULES_TSKSCHSRV 1
#define SERVERS_MODULES_TSKSCHRDF 1
#define SERVERS_MODULES_TSKSCHCSP 1
#define CELLCORE_MODULES_NETWORKPOLICYCSP 1
#define CELLCORE_MODULES_CELLTSP 1
#define CELLCORE_MODULES_RIL 1
#define CELLCORE_MODULES_RILENFORA 1
#define CELLCORE_MODULES_RILLOG 1
#define CELLCORE_MODULES_MUX07_10 1
#define CELLCORE_MODULES_SIM 1
#define CELLCORE_MODULES_SIMDRV 1
#define CELLCORE_MODULES_SMS_PROVIDERS 1
#define CELLCORE_MODULES_SMS 1
#define CELLCORE_MODULES_SMSDRV 1
#define CELLCORE_MODULES_WAP 1
#define CELLCORE_MODULES_WAPDRV 1
#define CELLCORE_MODULES_WWAN 1
#define CELLCORE_MODULES_CONNMGR 1
#define CELLCORE_MODULES_CSPOMADMCONN 1
#define CELLCORE_MODULES_CSPPROXY 1
#define CELLCORE_MODULES_CFGSPPOLICY 1
#define CELLCORE_MODULES_CSPRAS 1
#define CELLCORE_MODULES_ATCMDINT 1
#define CELLCORE_MODULES_GSMDLL 1
#define CELLCORE_MODULES_ATCISAMP 1
#define CELLCORE_MODULES_GSMEMUL 1
#define CELLCORE_MODULES_CELLCORE 1
#define CELLCORE_MODULES_CCOREUTL 1
#define CELLCORE_MODULES_RIL 1
#define CELLCORE_MODULES_SIM 1
#define CELLCORE_MODULES_SMS 1
#define OSSVCS_MODULES_OSSVCS 1
#define OSSVCS_MODULES_DMSRV 1
#define OSSVCS_MODULES_CONFIGMANAGER 1
#define OSSVCS_MODULES_CONFIGMANAGER2 1
#define OSSVCS_MODULES_PUSHPRXY 1
#define OSSVCS_MODULES_METABASEPROXY 1
#define OSSVCS_MODULES_METABASESERVICE 1
#define OSSVCS_MODULES_CONFIGMETABASE2 1
#define OSSVCS_MODULES_DMCSPS 1
#define OSSVCS_MODULES_ZIPCONTAINER 1
#define OSSVCS_MODULES_WSP 1
#define OSSVCS_MODULES_WSPPUSH 1
#define OSSVCS_MODULES_DIAGINFO 1
#define OSSVCS_MODULES_UTCORE 1
#define OSSVCS_MODULES_DMSAPI 1
#define OSSVCS_MODULES_OMADMSVC 1
#define OSSVCS_MODULES_DMSCHEDULERCALLBACK 1
#define OSSVCS_MODULES_REMOTEWIPESERVICE 1
#define OSSVCS_MODULES_REMOTEWIPECSP 1
#define OSSVCS_MODULES_CORESECURITYMODELCSP 1
#define OSSVCS_MODULES_CONNSTATE 1
#define OSSVCS_MODULES_FILELOGGER 1
#define SILVERLIGHT_MODULES_SLFX 1
#define SILVERLIGHT_MODULES_AGCORE 1
#define SILVERLIGHT_MODULES_NPCTRL 1
#define SILVERLIGHT_MODULES_NPCTRLUI 1
#define SEARCHPLATFORM_MODULES_DMDLUUID 1
#define SEARCHPLATFORM_MODULES_DATAMODEL 1
#define SEARCHPLATFORM_MODULES_SHELLRES 1
#define SEARCHPLATFORM_MODULES_IAFAPI 1
#define SEARCHPLATFORM_MODULES_INAPPFILTERINGCM 1
#define SEARCHPLATFORM_MODULES_INAPPFILTERINGCMRES 1
#define DEVICEFEEDBACK_MODULES_UIFSETTINGS 1
#define DEVICEFEEDBACK_MODULES_UIF 1
#define DEVICEFEEDBACK_MODULES_SQMDATA 1
#define DIRECTX_MODULES_AVCAPTURE 1
#define DIRECTX_MODULES_IPLAYAUDIO 1
#define DIRECTX_MODULES_FMSTUBPDD 1
#define DIRECTX_MODULES_AUDIOTUNERAPI 1
#define DIRECTX_MODULES_AUDIOTUNERMDD 1
#define DIRECTX_MODULES_CAMERAMDD 1
#define DIRECTX_MODULES_CAMERANULLPDD 1
#define DIRECTX_MODULES_MF 1
#define DIRECTX_MODULES_WMVDMOD 1
#define DIRECTX_MODULES_WMADMOD 1
#define DIRECTX_MODULES_WMADMOD 1
#define DIRECTX_MODULES_STRMBASE 1
#define DIRECTX_MODULES_QUARTZ 1
#define DIRECTX_MODULES_MSRLE32 1
#define DIRECTX_MODULES_ICM 1
#define DIRECTX_MODULES_MSDMO 1
#define DIRECTX_MODULES_WMVDMOE 1
#define DIRECTX_MODULES_CEDRM2 1
#define DIRECTX_MODULES_PLAYREADY 1
#define DIRECTX_MODULES_PLAYREADY_NOOBFUS 1
#define DIRECTX_MODULES_PLAYREADY_WHITEBOX 1
#define DIRECTX_MODULES_XDRMREMOTESERV 1
#define DIRECTX_MODULES_MULTIMEDIALAUNCHER 1
#define DIRECTX_MODULES_MIDIPARSER 1
#define DIRECTX_MODULES_MIDISYNTH 1
#define DIRECTX_MODULES_GSM610 1
#define DIRECTX_MODULES_MSADPCM 1
#define DIRECTX_MODULES_IMAADPCM 1
#define DIRECTX_MODULES_MSG711 1
#define DIRECTX_MODULES_AUDIORTGMGR 1
#define DIRECTX_MODULES_AUDIORTGENGINE 1
#define DIRECTX_MODULES_AUDIORTGBTHEXT 1
#define DIRECTX_MODULES_AUDIORTGPHONECLIENT 1
#define DIRECTX_MODULES_WAVEAPI 1
#define DIRECTX_MODULES_WAVEAPIC 1
#define APPPLATSVC_MODULES_PUSH 1
#define APPPLATSVC_MODULES_PUSHSVC 1
#define APPPLATSVC_MODULES_PACMANCLIENT 1
#define APPPLATSVC_MODULES_PACMANSERVER 1
#define APPPLATSVC_MODULES_EXECMANSERVER 1
#define APPPLATSVC_MODULES_NATIVEINSTALLER 1
#define APPPLATSVC_MODULES_NATIVEINSTALLERHOST 1
#define APPPLATSVC_MODULES_NATIVEINSTALLERINFO 1
#define APPPLATSVC_MODULES_NIHOSTAPPINSTALLER 1
#define APPPLATSVC_MODULES_NIHOSTAPPUNINSTALLER 1
#define APPPLATSVC_MODULES_DEVICEREG 1
#define MSF_MODULES_SYNCHRONIZATION 1
#define MSF_MODULES_SYNCHRONIZATIONRES 1
#define MSF_MODULES_FEEDSYNC 1
#define MSF_MODULES_METASTORE 1
#define MSF_MODULES_METASTORERES 1
#define WEBAPPS_MODULES_BROWSUI 1
#define WEBAPPS_MODULES_EEHOST 1
#define WEBAPPS_MODULES_ENTITYEXTRACTIONEXTENSION 1
#define WEBAPPS_MODULES_BROWSRESDLL 1
#define WEBAPPS_MODULES_IEXPLORE 1
#define WEBAPPS_MODULES_MTFBROWSERDS 1
#define WEBAPPS_MODULES_SUGGESTIONSBAR 1
#define WEBAPPS_MODULES_BROWSERSETTINGSHOST 1
#define WEBAPPS_MODULES_BROWSERSETTINGSCPL 1
#define DEVICEUPDATE_MODULES_DUASVC 1
#define DEVICEUPDATE_MODULES_DUAAPI 1
#define DEVICEUPDATE_MODULES_DUALOGGER 1
#define DEVICEUPDATE_MODULES_DUACLIENT 1
#define DEVICEUPDATE_MODULES_DUACLIENTRES 1
#define DEVICEUPDATE_MODULES_DUACLIENTUIRES 1
#define DEVICEUPDATE_MODULES_DUACLIENTSETTINGS 1
#define MTP_MODULES_MTPCLIENTDRVUSB 1
#define MTP_MODULES_MTPSVC 1
#define MTP_MODULES_MTPCLIENTDRVIP 1
#define MTP_MODULES_ZCONFIG_SERV 1
#define MTP_MODULES_ZMEDIA_SERV 1
#define MTP_MODULES_ZTRACE 1
#define MTP_MODULES_ZNET_SERV 1
#define MTP_MODULES_XHTTPDLL 1
#define MTP_MODULES_MTPHANDSHAKEPLUGIN 1
#define XNA_MODULES_XNAFRAMEWORK 1
#define XNA_MODULES_XNAFRAMEWORKGRAPHICS 1
#define XNA_MODULES_XNAFRAMEWORKGAMERSERVICES 1
#define XNA_MODULES_XNAAPPMODEL 1
#define XNA_MODULES_XNAFRAMEWORKCORE 1
#define RM_MODULES_MSDRM 1
#define RM_MODULES_SECPROC 1
#define RM_MODULES_SECPROC_TEST 1
#define RM_MODULES_RMACTIVATE 1
#define RM_MODULES_RMACTIVATE_TEST 1
#define RM_MODULES_RMUT_END2END 1
#define COMMSPLATFORM_MODULES_CHNGTRK 1
#define COMMSPLATFORM_MODULES_CEMAPI 1
#define COMMSPLATFORM_MODULES_MAPISERVICE 1
#define COMMSPLATFORM_MODULES_EXSMIME 1
#define COMMSPLATFORM_MODULES_TMAILUTL 1
#define COMMSPLATFORM_MODULES_COMMSENTITYEXTRACTION 1
#define COMMSPLATFORM_MODULES_PIMSTORE 1
#define COMMSPLATFORM_MODULES_PIMUTIL 1
#define COMMSPLATFORM_MODULES_PIMUTILUI 1
#define COMMSPLATFORM_MODULES_POSYNCSERVICES 1
#define COMMSPLATFORM_MODULES_PPROV 1
#define COMMSPLATFORM_MODULES_UNISTORE 1
#define COMMSPLATFORM_MODULES_ACCOUNTSETTINGS 1
#define COMMSPLATFORM_MODULES_ACCOUNTACCESSOR 1
#define COMMSPLATFORM_MODULES_BTSERV 1
#define COMMSPLATFORM_MODULES_BTSCLI 1
#define APPPLATFORM_MODULES_NOTIFICATION 1
#define APPPLATFORM_MODULES_EMCLIENT 1
#define APPPLATFORM_MODULES_NOTIFICATIONAGENT 1
#define APPPLATFORM_MODULES_TESTEXECLI 1
#define APPPLATFORM_MODULES_UICONTROLS 1
#define APPPLATFORM_MODULES_NYTIMES 1
#define APPPLATFORM_MODULES_TASKHOST 1
#define APPPLATFORM_MODULES_LICENSEINTEROP 1
#define APPPLATFORM_MODULES_LICENSE 1
#define APPPLATFORM_MODULES_COREX 1
#define APPPLATFORM_MODULES_SYSTEM 1
#define APPPLATFORM_MODULES_MICROSOFT 1
#define APPPLATFORM_MODULES_MICROSOFT 1
#define APPS_MODULES_MGDWINMOB 1
#define APPS_MODULES_MGDCFG 1
#define APPS_MODULES_MGDTELAPI 1
#define APPS_MODULES_PERFMAN 1
#define APPS_MODULES_FSDSPY 1
#define APPS_MODULES_WLIDUI 1
#define APPS_MODULES_WLIDCONFIG 1
#define APPS_MODULES_WLIDUIX 1
#define APPS_MODULES_MCF 1
#define APPS_MODULES_MDDRM 1
#define APPS_MODULES_RMACTIVATE 1
#define APPS_MODULES_CEWS 1
#define APPS_MODULES_MCF 1
#define APPS_MODULES_MDDRM 1
#define APPS_MODULES_IRMACTIVATE 1
#define APPS_MODULES_IRMTEST 1
#define APPS_MODULES_RMACTIVATE 1
#define APPS_MODULES_SYNCRES 1
#define APPS_MODULES_PUSHROUTER 1
#define APPS_MODULES_CORESECPROVIDERS 1
#define APPS_MODULES_CFGHOST 1
#define APPS_MODULES_OMADMPRC 1
#define APPS_MODULES_OMADMCLIENT 1
#define APPS_MODULES_COREDPUS 1
#define APPS_MODULES_CERTINSTALLER 1
#define APPS_MODULES_CERTIFICATECSP 1
#define APPS_MODULES_COLDINIT 1
#define APPS_MODULES_CIPHASE2 1
#define APPS_MODULES_LASSEX 1
#define APPS_MODULES_DEVICELOCKDATASOURCE 1
#define APPS_MODULES_LASSRES 1
#define APPS_MODULES_IMGUPDATECSP 1
#define APPS_MODULES_DULOGGER 1
#define APPS_MODULES_SYSTEMRESTORE 1
#define APPS_MODULES_SYSSNAP 1
#define APPS_MODULES_IPSECVPNRES 1
#define APPS_MODULES_SIMPLEPINLAP 1
#define APPS_MODULES_STRONGPINLAP 1
#define APPS_MODULES_KEYLOCKLAP 1
#define APPS_MODULES_LAPRES 1
#define APPS_MODULES_EXCHANGEARC 1
#define APPS_MODULES_MYPHONELAP 1
#define WEBSEARCH_MODULES_WEBSEARCH 1
#define WEBSEARCH_MODULES_SEARCHMAPSCM 1
#define WEBSEARCH_MODULES_SEARCHMAPSCMRES 1
#define WEBSEARCH_MODULES_KEYWORDSDATASTORE 1
#define WEBSEARCH_MODULES_SEARCHMAPSSETTINGS 1
#define WEBSEARCH_MODULES_SEARCHMAPSSETTINGSRES 1
#define WEBSEARCH_MODULES_MAPCONTROL 1
#define WEBSEARCH_MODULES_ONLINESUGGESTIONSDS 1
#define SKYBOX_MODULES_MYPHONECPLCM 1
#define SKYBOX_MODULES_MYPHONECPL 1
#define SKYBOX_MODULES_MYPHONECPLPLUGINS 1
#define SKYBOX_MODULES_MYPHONECSP 1
#define SKYBOX_MODULES_MYPHONEMAILRULE 1
#define SKYBOX_MODULES_MYPHONERES 1
#define SKYBOX_MODULES_MYPHONETASKSCLIENT 1
#define SKYBOX_MODULES_MYPHONETASKSRUNTIME 1
#define SKYBOX_MODULES_MYPHONEBRRUNTIME 1
#define SKYBOX_MODULES_MYPHONEUIX 1
#define SKYBOX_MODULES_MYPHONEUIXRES 1
#define COREDLL_COREMAIN 1
#define COREDLL_THUNKS 1
#define COREDLL_COREPOLICY 1
#define COREDLL_SHOWERR 1
#define COREDLL_CORECRT 1
#define COREDLL_CORESTRW 1
#define COREDLL_CORESIP 1
#define COREDLL_REGEXT 1
#define COREDLL_COREDLL_HANDLEARRAY 1
#define COREDLL_CCPSELECT 1
#define COREDLL_TNOTIFY 1
#define COREDLL_TAPILIB 1
#define COREDLL_TBTCORE 1
#define COREDLL_MESSAGEDIALOGBOXTHUNK 1
#define COREDLL_MMACM 1
#define COREDLL_MMACMUI 1
#define COREDLL_MMWAVE 1
#define COREDLL_MMSND 1
#define COREDLL_MMMIX 1
#define COREDLL_WAVEAPICFWD 1
#define COREDLL_BATTERY 1
#define COREDLL_NLED 1
#define COREDLL_ASYNCIO 1
#define COREDLL_DEVENUM 1
#define COREDLL_DEVLOAD 1
#define COREDLL_COREBUILDINFO 1
#define COREDLL_COREVERSIONPKG 1
#define COREDLL_FIBER 1
#define COREDLL_COREIMM 1
#define COREDLL_CORESIOA 1
#define COREDLL_CORESTRA 1
#define COREDLL_CORESIOW 1
#define COREDLL_CRYPTAPI 1
#define COREDLL_FMTRES 1
#define COREDLL_FMTMSG 1
#define COREDLL_SERDEV 1
#define COREDLL_MULTIUI 1
#define COREDLL_CORELOC 1
#define COREDLL_CRT_CPP_EH_AND_RTTI 1
#define COREDLL_FULL_CRT 1
#define COREDLL_CRYPTHASH 1
#define COREDLL_RSA32_COREDLL 1
#define KCOREDLL_KCOREMAIN 1
#define KCOREDLL_KTHUNKS 1
#define KCOREDLL_KCOREPOLICY 1
#define KCOREDLL_SHOWERR 1
#define KCOREDLL_CORECRT 1
#define KCOREDLL_CORESTRW 1
#define KCOREDLL_CORESIP 1
#define KCOREDLL_REGEXT 1
#define KCOREDLL_COREDLL_HANDLEARRAY 1
#define KCOREDLL_CCPSELECT 1
#define KCOREDLL_TNOTIFY 1
#define KCOREDLL_TAPILIB 1
#define KCOREDLL_TBTCORE 1
#define KCOREDLL_MESSAGEDIALOGBOXTHUNK 1
#define KCOREDLL_MMACM 1
#define KCOREDLL_MMACMUI 1
#define KCOREDLL_MMWAVE 1
#define KCOREDLL_MMSND 1
#define KCOREDLL_MMMIX 1
#define KCOREDLL_WAVEAPICFWD 1
#define KCOREDLL_BATTERY 1
#define KCOREDLL_NLED 1
#define KCOREDLL_ASYNCIO 1
#define KCOREDLL_DEVENUM 1
#define KCOREDLL_DEVLOAD 1
#define KCOREDLL_COREBUILDINFO 1
#define KCOREDLL_COREVERSIONPKG 1
#define KCOREDLL_FIBER 1
#define KCOREDLL_COREIMM 1
#define KCOREDLL_CORESIOA 1
#define KCOREDLL_CORESTRA 1
#define KCOREDLL_CORESIOW 1
#define KCOREDLL_CRYPTAPI 1
#define KCOREDLL_FMTRES 1
#define KCOREDLL_FMTMSG 1
#define KCOREDLL_SERDEV 1
#define KCOREDLL_MULTIUI 1
#define KCOREDLL_CORELOC 1
#define KCOREDLL_CRT_CPP_EH_AND_RTTI 1
#define KCOREDLL_FULL_CRT 1
#define KCOREDLL_CRYPTHASH 1
#define KCOREDLL_RSA32_COREDLL 1
#define NK_NKCOMPR 1
#define NK_NKTZINIT 1
#define NK_NKMAPFILE 1
#define NK_NKMSGQ 1
#define NK_KACL 1
#define NKLOADER_NKLDR 1
#define OEM_NKSTUB 1
#define OEM_OEMMAIN 1
#define OEM_OEMMAIN_STATICKITL 1
#define WINSOCK_SSLSOCK 1
#define IMGUPD_KEY_FILE 1
#define IMGUPD_CIF_FILE 1
#define IMGUPD_SOF_FILE 1
#define IMGUPD_FSDMGR_INI 1
#define IMGFS_IMGFS_NOWRITE 1
#define FILESYS_FSHEAP 1
#define FILESYS_FSMAIN 1
#define FILESYS_FSPROFILE 1
#define FILESYS_FSADVERTISE 1
#define FILESYS_FSEVENTLOG 1
#define FILESYS_FSREGHIVE 1
#define FILESYS_FSSECUREWIPE 1
#define FILESYS_FSREPLBIT 1
#define FILESYS_FSDBASE 1
#define FILESYS_FSPASS 1
#define FILESYS_FSACL 1
#define FILESYS_ADB 1
#define CECOMPR_XPRDECOMP 1
#define OLE32_DCOMOLE 1
#define OLE32_STG 1
#define OLEAUT32_OAALL 1
#define OLEAUT32_IDISPPROXY 1
#define QUARTZ_QUARTZ0 1
#define QUARTZ_AMUTIL 1
#define QUARTZ_FGCTL 1
#define QUARTZ_FILGRAPH 1
#define QUARTZ_QUARTZ1 1
#define QUARTZ_NULLAUDIORENDERER 1
#define QUARTZ_WAVEOUT 1
#define QUARTZ_WAVEMSR 1
#define QUARTZ_AVIMSR 1
#define QUARTZ_AVIDEC 1
#define QUARTZ_MFBRIDGE 1
#define QUARTZ_MSSSOURCE 1
#define QUARTZ_ACMWRAP 1
#define QUARTZ_DMOWRAP 1
#define QUARTZ_URLRDR 1
#define QUARTZ_QUARTZ2 1
#define QUARTZ_ASYNCRDR 1
#define QUARTZ_QTZBASE 1
#define QUARTZ_IMGSINK 1
#define QUARTZ_QUARTZ3 1
#define QUARTZ_VMRALLOCLIB 1
#define QUARTZ_VMRALLOCATORPRESENTER 1
#define QUARTZ_VMRWINDOWMANAGER 1
#define QUARTZ_VMRIMAGESYNC 1
#define QUARTZ_VMRMIXER 1
#define QUARTZ_VMRRENDERER 1
#define QUARTZ_ASFWRITER 1
#define QUARTZ_ASFMUXCORE 1
#define QUARTZ_WAVEIN 1
#define QUARTZ_VIDCAP 1
#define QUARTZ_FILCAP 1
#define QUARTZ_SCMDOUT 1
#define QUARTZ_FILEREND 1
#define QUARTZ_WMT_STRMCORE 1
#define QUARTZ_WMT_SPLITTER 1
#define QUARTZ_ACMOBJ 1
#define QUARTZ_ICMOBJ 1
#define QUARTZ_M3UPLAYL 1
#define QUARTZ_ASXPLAYL 1
#define QUARTZ_XMLPLAYL 1
#define QUARTZ_URLGRAB 1
#define QUARTZ_URLOBJ 1
#define QUARTZ_WMT_HTTPSTRM 1
#define QUARTZ_WMT_MSBSTRM 1
#define QUARTZ_WMT_NETHELP 1
#define QUARTZ_WMT_FILESTRM 1
#define QUARTZ_PLAYREADYDRM 1
#define QUARTZ_CONNECTHELPER 1
#define QUARTZ_QUARTZ4 1
#define QUARTZ_COLOUR 1
#define QUARTZ_BUFFILTER 1
#define QUARTZ_COLOUR 1
#define QUARTZ_GENSTREAMER 1
#define QUARTZ_QUARTZ4 1
#define QUARTZ_COLOUR 1
#define QUARTZ_BUFFILTER 1
#define QUARTZ_COLOUR 1
#define QUARTZ_GENSTREAMER 1
#define QUARTZ_QUARTZ3 1
#define QUARTZ_VMRALLOCLIB 1
#define QUARTZ_VMRALLOCATORPRESENTER 1
#define QUARTZ_VMRWINDOWMANAGER 1
#define QUARTZ_VMRIMAGESYNC 1
#define QUARTZ_VMRMIXER 1
#define QUARTZ_VMRRENDERER 1
#define QUARTZ_ASFWRITER 1
#define QUARTZ_ASFMUXCORE 1
#define QUARTZ_WAVEIN 1
#define QUARTZ_VIDCAP 1
#define QUARTZ_FILCAP 1
#define QUARTZ_SCMDOUT 1
#define QUARTZ_FILEREND 1
#define QUARTZ_WMT_STRMCORE 1
#define QUARTZ_WMT_SPLITTER 1
#define QUARTZ_ACMOBJ 1
#define QUARTZ_ICMOBJ 1
#define QUARTZ_M3UPLAYL 1
#define QUARTZ_ASXPLAYL 1
#define QUARTZ_XMLPLAYL 1
#define QUARTZ_URLGRAB 1
#define QUARTZ_URLOBJ 1
#define QUARTZ_WMT_HTTPSTRM 1
#define QUARTZ_WMT_MSBSTRM 1
#define QUARTZ_WMT_NETHELP 1
#define QUARTZ_WMT_FILESTRM 1
#define QUARTZ_PLAYREADYDRM 1
#define QUARTZ_CONNECTHELPER 1
#define QUARTZ_QUARTZ3 1
#define QUARTZ_VMRALLOCLIB 1
#define QUARTZ_VMRALLOCATORPRESENTER 1
#define QUARTZ_VMRWINDOWMANAGER 1
#define QUARTZ_VMRIMAGESYNC 1
#define QUARTZ_VMRMIXER 1
#define QUARTZ_VMRRENDERER 1
#define QUARTZ_ASFWRITER 1
#define QUARTZ_ASFMUXCORE 1
#define QUARTZ_WAVEIN 1
#define QUARTZ_VIDCAP 1
#define QUARTZ_FILCAP 1
#define QUARTZ_SCMDOUT 1
#define QUARTZ_FILEREND 1
#define QUARTZ_WMT_STRMCORE 1
#define QUARTZ_WMT_SPLITTER 1
#define QUARTZ_ACMOBJ 1
#define QUARTZ_ICMOBJ 1
#define QUARTZ_M3UPLAYL 1
#define QUARTZ_ASXPLAYL 1
#define QUARTZ_XMLPLAYL 1
#define QUARTZ_URLGRAB 1
#define QUARTZ_URLOBJ 1
#define QUARTZ_WMT_HTTPSTRM 1
#define QUARTZ_WMT_MSBSTRM 1
#define QUARTZ_WMT_NETHELP 1
#define QUARTZ_WMT_FILESTRM 1
#define QUARTZ_PLAYREADYDRM 1
#define QUARTZ_CONNECTHELPER 1
#define EXSMIME_DSTRUCT 1
#define EXSMIME_EXSMIME_COMMON 1
#define PIMUTIL_PARSERX 1
#define PIMUTIL_PARSERXSTUBS_SMARTFON 1
#define PIMUTIL_PARSERO11 1

// <SYSGENS>
// SYSGEN_ACCOUNTDB
// SYSGEN_ACL
// SYSGEN_ACM_GSM610
// SYSGEN_ASSOCENG
// SYSGEN_ASYNCMAC
// SYSGEN_ATADISK
// SYSGEN_ATL
// SYSGEN_AUDIO
// SYSGEN_AUDIOTUNER
// SYSGEN_AUDIO_ACM
// SYSGEN_AUDIO_AUDIORTGMGR
// SYSGEN_AUTH
// SYSGEN_AUTH_NTLM
// SYSGEN_AUTH_SCHANNEL
// SYSGEN_AVCAPTURE
// SYSGEN_BATTERY
// SYSGEN_BTH
// SYSGEN_BTH_A2DP
// SYSGEN_BTH_AVCTP
// SYSGEN_BTH_AVDTP
// SYSGEN_BTH_AVRCP
// SYSGEN_CACHEFILT
// SYSGEN_CCPSELECT
// SYSGEN_CECOMPR_XPR_DECOMPRESS
// SYSGEN_CEDDK
// SYSGEN_CELLCORE
// SYSGEN_CELLCORE_710MUX
// SYSGEN_CELLCORE_ATCI
// SYSGEN_CELLCORE_CELLTSP
// SYSGEN_CELLCORE_EVENTLOG
// SYSGEN_CELLCORE_RIL
// SYSGEN_CELLCORE_RILLOG
// SYSGEN_CELLCORE_SIM
// SYSGEN_CELLCORE_SMS
// SYSGEN_CELLCORE_WAP
// SYSGEN_CELLCORE_WWAN
// SYSGEN_CEPERF
// SYSGEN_CERTS
// SYSGEN_CERTS_PFX
// SYSGEN_CNG_CORE
// SYSGEN_CNG_KEY
// SYSGEN_COMMCTRL
// SYSGEN_CONNMGR
// SYSGEN_CONNMGR2
// SYSGEN_CORELOC
// SYSGEN_COREOSLAUNCH
// SYSGEN_CORESTRA
// SYSGEN_CPP_EH_AND_RTTI
// SYSGEN_CPP_SEH
// SYSGEN_CREDMAN
// SYSGEN_CRYPTMSG
// SYSGEN_CRYPTO
// SYSGEN_CRYPTO_DSSDH
// SYSGEN_CXPORT
// SYSGEN_DCOM
// SYSGEN_DDRAW
// SYSGEN_DEVHEALTH
// SYSGEN_DEVICE
// SYSGEN_DHCP
// SYSGEN_DHCPSRV
// SYSGEN_DMSRV
// SYSGEN_DNSAPI
// SYSGEN_DOTNETV2
// SYSGEN_DOTNETV37
// SYSGEN_DOTNETV37_SMARTFON
// SYSGEN_DOTNETV37_SUPPORT
// SYSGEN_DSHOW
// SYSGEN_DSHOW_ACMWRAP
// SYSGEN_DSHOW_AUDIO
// SYSGEN_DSHOW_AVI
// SYSGEN_DSHOW_CAPTURE
// SYSGEN_DSHOW_DISPLAY
// SYSGEN_DSHOW_DMO
// SYSGEN_DSHOW_GENERICSTREAMER
// SYSGEN_DSHOW_ICM
// SYSGEN_DSHOW_IMAADPCM
// SYSGEN_DSHOW_MFBRIDGE
// SYSGEN_DSHOW_MIDIPARSER
// SYSGEN_DSHOW_MIDISYNTH
// SYSGEN_DSHOW_MP3
// SYSGEN_DSHOW_MPEGA
// SYSGEN_DSHOW_MPEGSPLITTER
// SYSGEN_DSHOW_MPEGV
// SYSGEN_DSHOW_MSADPCM
// SYSGEN_DSHOW_MSG711
// SYSGEN_DSHOW_MSRLE
// SYSGEN_DSHOW_MSSSOURCE
// SYSGEN_DSHOW_NULLAUDIO
// SYSGEN_DSHOW_URLRDR
// SYSGEN_DSHOW_VMR
// SYSGEN_DSHOW_WAV
// SYSGEN_DSHOW_WAVEOUT
// SYSGEN_DSHOW_WMA
// SYSGEN_DSHOW_WMA_VOICE
// SYSGEN_DSHOW_WMT
// SYSGEN_DSHOW_WMT_ASXV1
// SYSGEN_DSHOW_WMT_ASXV2
// SYSGEN_DSHOW_WMT_ASXV3
// SYSGEN_DSHOW_WMT_DRMOCX
// SYSGEN_DSHOW_WMT_HTTP
// SYSGEN_DSHOW_WMT_LOCAL
// SYSGEN_DSHOW_WMT_MMS
// SYSGEN_DSHOW_WMT_MULTI
// SYSGEN_DSHOW_WMT_PLAYREADYDRM
// SYSGEN_DSHOW_WMV
// SYSGEN_DSHOW_XDRMREMOTE
// SYSGEN_DSTSVC
// SYSGEN_DTPT
// SYSGEN_EAP
// SYSGEN_EAPHOST
// SYSGEN_EDB
// SYSGEN_ETHERNET
// SYSGEN_ETH_80211
// SYSGEN_ETH_80211_NWIFI
// SYSGEN_EVGEN
// SYSGEN_FATFS
// SYSGEN_FDRM2
// SYSGEN_FLASHMDD
// SYSGEN_FMTMSG
// SYSGEN_FMTRES
// SYSGEN_FSDBASE
// SYSGEN_FSDMGR
// SYSGEN_FSREGHIVE
// SYSGEN_FSREPLBIT
// SYSGEN_FSROMONLY
// SYSGEN_FULL_CRT
// SYSGEN_GDI_ALPHABLEND
// SYSGEN_GPSID
// SYSGEN_IE7_ACTXPRXY
// SYSGEN_IE7_DXTMSFT
// SYSGEN_IE7_DXTRANS
// SYSGEN_IE7_GESTURESUPPORT
// SYSGEN_IE7_IEFRAME
// SYSGEN_IE7_IETHEME
// SYSGEN_IE7_IETHMWM
// SYSGEN_IE7_IMGCACHE
// SYSGEN_IE7_IMGUTIL
// SYSGEN_IE7_JSCRIPT
// SYSGEN_IE7_MLANG
// SYSGEN_IE7_MSHTML
// SYSGEN_IE7_PNGFILT
// SYSGEN_IE7_URLMON
// SYSGEN_IE7_VBSCRIPT
// SYSGEN_IE7_WININET
// SYSGEN_IMAGING
// SYSGEN_IMAGING_BMP_DECODE
// SYSGEN_IMAGING_BMP_ENCODE
// SYSGEN_IMAGING_GIF_DECODE
// SYSGEN_IMAGING_GIF_ENCODE
// SYSGEN_IMAGING_JPG_DECODE
// SYSGEN_IMAGING_JPG_ENCODE
// SYSGEN_IMAGING_PNG_DECODE
// SYSGEN_IMAGING_PNG_ENCODE
// SYSGEN_IMGFS
// SYSGEN_IMGUPD
// SYSGEN_IMGUPD_ALL
// SYSGEN_IMGUPD_KEY
// SYSGEN_IMM
// SYSGEN_INTERNET_SHARING
// SYSGEN_IPHLPAPI
// SYSGEN_IPLAYAUDIO
// SYSGEN_KBD_ARABIC_101
// SYSGEN_KBD_GUJARATI
// SYSGEN_KBD_HEBREW
// SYSGEN_KBD_HINDI_TRADITIONAL
// SYSGEN_KBD_JAPANESE
// SYSGEN_KBD_JAPANESE_NEC
// SYSGEN_KBD_KANNADA
// SYSGEN_KBD_KOREAN
// SYSGEN_KBD_MARATHI
// SYSGEN_KBD_PUNJABI
// SYSGEN_KBD_RUSSIAN
// SYSGEN_KBD_TAMIL
// SYSGEN_KBD_TELUGU
// SYSGEN_KBD_THAI_KEDMANEE
// SYSGEN_KBD_US
// SYSGEN_LDAP
// SYSGEN_LOCALAUDIO
// SYSGEN_LOCATION_ALGOS_RESOLVER
// SYSGEN_LOCATION_CROWDSOURCING
// SYSGEN_LOCATION_FRAMEWORK
// SYSGEN_LOCATION_GPS_PROVIDER
// SYSGEN_LOCATION_LATLON_RESOLVER
// SYSGEN_LOCATION_LFORIONPROVIDER
// SYSGEN_LOCATION_LFTESTPLUGIN
// SYSGEN_LOCATION_LSTIMEPLUGIN
// SYSGEN_LOCATION_PLACES_RESOLVER
// SYSGEN_LOCATION_RIL_PROVIDER
// SYSGEN_LOCATION_WIFICELL_RESOLVER
// SYSGEN_LOCATION_WIFI_PROVIDER
// SYSGEN_LVMOD_STUB
// SYSGEN_MF
// SYSGEN_MINGDI
// SYSGEN_MINGWES
// SYSGEN_MINICOM
// SYSGEN_MININPUT
// SYSGEN_MINWMGR
// SYSGEN_MODEM
// SYSGEN_MSF
// SYSGEN_MSGQUEUE
// SYSGEN_MSIME
// SYSGEN_MSPART
// SYSGEN_MSXML_DATA_ISLANDS
// SYSGEN_MSXML_DOM
// SYSGEN_MSXML_ERROR_STRINGS
// SYSGEN_MSXML_HTTP
// SYSGEN_MSXML_MIMEVIEWER
// SYSGEN_MSXML_SAX
// SYSGEN_MSXML_XQL
// SYSGEN_MSXML_XSLT
// SYSGEN_MTF
// SYSGEN_MTPZ
// SYSGEN_MULTIUI
// SYSGEN_NDIS
// SYSGEN_NDISUIO
// SYSGEN_NETLOG
// SYSGEN_NETWORK_POLICY
// SYSGEN_NKCOMPR
// SYSGEN_NKMAPFILE
// SYSGEN_NKTZINIT
// SYSGEN_NLED
// SYSGEN_NOTIFY
// SYSGEN_OBEX_SERVER
// SYSGEN_OFFICE
// SYSGEN_OLE
// SYSGEN_OLE_GUIDS
// SYSGEN_OLE_STG
// SYSGEN_OPENMP
// SYSGEN_OSTEST
// SYSGEN_PM
// SYSGEN_PM_PDA
// SYSGEN_POLICYXML
// SYSGEN_PPP
// SYSGEN_PPTP
// SYSGEN_RAMDISK
// SYSGEN_RAWFS
// SYSGEN_REDIR
// SYSGEN_RELFSD
// SYSGEN_RELIABILITY
// SYSGEN_REPLACE_SQMCONN
// SYSGEN_ROMFILTER
// SYSGEN_RPCRT4
// SYSGEN_RTTI
// SYSGEN_SDBUS
// SYSGEN_SD_MEMORY
// SYSGEN_SENSORS
// SYSGEN_SERDEV
// SYSGEN_SERVICES
// SYSGEN_SETPROXY
// SYSGEN_SHELL
// SYSGEN_SILVERLIGHT
// SYSGEN_SKYBOX
// SYSGEN_SQLCOMPACT
// SYSGEN_SQLCOMPACTMP
// SYSGEN_SQM_ENGINE
// SYSGEN_SQM_UPLOAD
// SYSGEN_STATE_NOTIFICATIONS
// SYSGEN_STDIO
// SYSGEN_STDIOA
// SYSGEN_STOREMGR
// SYSGEN_STRSAFE
// SYSGEN_TAPI
// SYSGEN_TASK_SCHEDULER
// SYSGEN_TCPIP
// SYSGEN_TFAT
// SYSGEN_TIMEZONES
// SYSGEN_TOOLHELP
// SYSGEN_UIPROXY
// SYSGEN_UNIFIEDBLOCK
// SYSGEN_UNIFIEDPAIR
// SYSGEN_UNIMODEM
// SYSGEN_USB
// SYSGEN_USBFN
// SYSGEN_USBFN_COMPOSITE
// SYSGEN_USBFN_ETHERNET
// SYSGEN_USBFN_SERIAL
// SYSGEN_USB_HID_CLIENTS
// SYSGEN_USB_STORAGE
// SYSGEN_VEM
// SYSGEN_WININET
// SYSGEN_WINSOCK
// SYSGEN_WLIDSVC
// SYSGEN_XMLLITE
// SYSGEN_XNA
// </SYSGENS>

// <_TGTS>
// _TGTCPU=X86
// _TGTCPUFAMILY=X86
// _TGTOS=CE
// _TGTPLAT=NOPLAT
// _TGTPROJ=SMARTFON
// </_TGTS>
#endif
